---
services:
- name: test
  src: ./test-src
  publishers:
   - test-pub1
  subscribers:
   - test1-pub1
  build: go build main.go
  run: go run main.go

- name: test1
  src: ./test1-src
  publishers:
   - test1-pub1
  subscribers:
   - test-pub1
  build: go build main.go
  run: go run main.go
